### ISSUE TITLE
Check that files_external_dropbox is working OK after Guzzle7 core update for core 10.11

### ISSUE THREAD

**Issue by kiranadh1452** [owncloud/files_external_dropbox#137]
Check the files_external_dropbox with core 10.10 and make sure that any existing problems have issues.

Try again with current core master (to be 10.11 release), and raise issues for any new problems.

Related to issue https://github.com/owncloud/core/issues/39387

**Comment by kiranadh1452** [comment]
## Core 10.11

- Mount Dropbox: :heavy_check_mark:
- View Files: :heavy_check_mark: 
- Download Files: :heavy_check_mark: 
- Delete Files: :heavy_check_mark: 
- Upload Files: :x:  (Gives error message : `Call to undefined function GuzzleHttp\Psr7\stream_for()`)
- Rename Files: :heavy_check_mark: 
- Federated Sharing of file: :heavy_check_mark: 
- Federated Sharing of folder: 
  - Upload inside the shared folder: :x: (Error message : `Failed to write file contents: GuzzleHttp\Exception\ServerException: Server error response [url] http://localhost/core/public.php/webdav/test.txt [status code] 500 [reason phrase] Internal Server Error`)

## Core 10.10
Error Message:
> App "External Storage: Dropbox" cannot be installed because the following dependencies are not fulfilled: `ownCloud 10.11 or higher is required.`

**Comment by phil-davis** [comment]
> Error Message

To compare on ownCloud 10.10 you need to use the current release of the app, rather than current master of the app repo.

**Comment by kiranadh1452** [comment]
# Final Report 

## Core 10.10

- Mount Dropbox: :heavy_check_mark:
- View Files: :heavy_check_mark: 
- Download Files: :heavy_check_mark: 
- Delete Files: :heavy_check_mark: 
- Upload Files: :heavy_check_mark: 
- Rename Files: :heavy_check_mark: 
- Federated Sharing of file: :heavy_check_mark: 
- Federated Sharing of folder: :heavy_check_mark: 

## Core 10.11

- Mount Dropbox: :heavy_check_mark:
- View Files: :heavy_check_mark: 
- Download Files: :heavy_check_mark: 
- Delete Files: :heavy_check_mark: 
- Upload Files: :x:  (Gives error message : `Call to undefined function GuzzleHttp\Psr7\stream_for()`)
- Rename Files: :heavy_check_mark: 
- Federated Sharing of file: :heavy_check_mark: 
- Federated Sharing of folder: 
  - Upload inside the shared folder: :x: (Error message : `Failed to write file contents: GuzzleHttp\Exception\ServerException: Server error response [url] http://localhost/core/public.php/webdav/test.txt [status code] 500 [reason phrase] Internal Server Error`)
