### ISSUE TITLE
Heavy database use

### ISSUE THREAD

**Issue by neemzy** [owncloud/files_external_dropbox#16]
As mentioned in https://github.com/owncloud/files_external_dropbox/issues/14#issuecomment-336513109 I'm getting a heavy database usage when trying to sync locally files coming from Dropbox through this app, which leads to a lot of timeouts. It only happens when I enable my Dropbox as external storage, everything else runs fine OC-wise.

Log excerpt:

```
PHP Fatal error:  Uncaught exception 'Doctrine\\DBAL\\DBALException' with message 'Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [1040] Too many connections' in /path/to/owncloud/lib/private/DB/Connection.php:63\nStack trace:\n#0 /path/to/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\\DB\\Connection->connect()\n#1 /path/to/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\\DBAL\\Connection->getDatabasePlatformVersion()\n#2 /path/to/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\\DBAL\\Connection->detectDatabasePlatform()\n#3 /path/to/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(623): Doctrine\\DBAL\\Connection->getDatabasePlatform()\n#4 /path/to/owncloud/lib/private/DB/Connection.php(146): Doctrine\\DBAL\\Connection->setTransactionIsolation(2)\n#5 /path/to/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(172): OC\\DB\\Connection->__construct(Array, Object(D in /path/to/owncloud/lib/private/DB/Connection.php on line 63
```

I'm using MariaDB; I increased `max_connections` from 100 to 10000 to no avail.

Edit: I'm now getting `'SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction'`; I tried running `SET GLOBAL innodb_lock_wait_timeout = 5000;` and `SET innodb_lock_wait_timeout = 5000;` but that didn't help either.

**Comment by PVince81** [comment]
@neemzy is that the full stack trace ?

The Dropbox app has some caching mechanism in place so I expect it shouldn't cause that many DB calls.

Do you have many files in the storage ?

**Comment by guruz** [comment]
Also could try https://stackoverflow.com/a/6479183/2941

**Comment by neemzy** [comment]
@PVince81 This is the full stack trace indeed. And my DB account is reasonably large, but it worked flawlessly with the old version.

**Comment by PVince81** [comment]
@neemzy when exactly is the error happening ? When viewing the file listing ? When syncing ?

You could try to close all clients and try accessing the mount with a Webdav client and see if it happens there too.

**Comment by neemzy** [comment]
@PVince81 "when trying to sync locally files coming from Dropbox through this app"

**Comment by PVince81** [comment]
Since we don't have the full stack trace, we need to find out what operation is causing the issue. It could be: PROPFIND (listing files), PUT (uploading files) or GET (downloading files).

So in your case it's about an uploading sync ?

**Comment by neemzy** [comment]
I set up Dropbox as external storage on my ownCloud instance.
I then tried to retrieve those files locally on my Windows computer by ticking the newly available checkbox in the client.
It failed with a "Server replied: Origin timeout" message.
I checked my server's logs and pasted everything I have here.

**Comment by guruz** [comment]
Maybe you get a clue from doing https://github.com/owncloud/files_external_dropbox/issues/16#issuecomment-336866675
That should also show which connection is trying what query?

**Comment by neemzy** [comment]
Isn't "Too many connections" related to a number of connections to the database, as opposed to anything query-related?

**Comment by PVince81** [comment]
ownCloud normally only opens a single DB connection per PHP request.

Maybe something else is happening that is preventing existing connections to be closed in a clean way.

**Comment by guruz** [comment]
> Isn't "Too many connections" related to a number of connections to the database, as opposed to anything query-related?

Yes, but you would see what query from which connection is stuffing the server and could deduce from that which request or background job is triggering this.

**Comment by neemzy** [comment]
> ownCloud normally only opens a single DB connection *per PHP request*.

That may be the key point here, given we're in an AJAX context. I'll try to find some time to log my database as requested.

**Comment by neemzy** [comment]
> ownCloud normally only opens a single DB connection *per PHP request*.

That may be the key point here, given we're in an AJAX context. I'll try to find some time to log my database as requested.

**Comment by neemzy** [comment]
@PVince81 @guruz Here is the full log for my database for a local sync trial of my Dropbox-based folder: https://dpaste.neemzy.org/paste/59eda83cefbb5e4070bc4390#shell

It begins when I first tick the checkbox for this folder on my client (OSX, this time) and ends after failing once with the aforementioned error, trying again and failing again.

Maybe I should also mention I find myself running the following on a regular basis (if I don't, my OC instance stops working): `SET GLOBAL binlog_format = "MIXED"`.

**Comment by neemzy** [comment]
@PVince81 @guruz Hi guys, did anyone get a chance to look into this? May I provide more information to help?

**Comment by guruz** [comment]
@neemzy I'd have expected to see a lot of requests at the same second (or close by) but the log doesn't.. mhm.
The ```Connect``` and ```Quit``` looks balanced too.

Maybe https://stackoverflow.com/questions/3638689/how-to-see-full-query-from-show-processlist and 
https://alvinalexander.com/blog/post/mysql/how-show-open-database-connections-mysql can help?

CC @Hemant-Mann maybe..

**Comment by Hemant-Mann** [comment]
Agree with @guruz
@neemzy You should enable the sync then may be try to see which queries are taking how much time.

The only slow component of the app while syncing the files is the request to the Dropbox API which gets the contents of a directory and for a single AJAX request this list is stored in memory to prevent subsequent calls to the API just to fetch metadata about files/folders

**Comment by Hemant-Mann** [comment]
@neemzy Any improvements with the 1.0.1 version of the app?

**Comment by neemzy** [comment]
I've finally been able to synchronize my Dropbox account locally by restarting the database on my server. I suspect some third-party load on my end was the root cause. I'll still update and let you know if anything interesting happens, but in the meantime I reckon we can close this issue. Thanks for your work!
