### ISSUE TITLE
Release plan for first version

### ISSUE THREAD

**Issue by PVince81** [owncloud/files_external_dropbox#2]
The main goal for now is to get the first release out before end of September where Dropbox API v1 is out. Performance might not be good but being able to keep access to the data is more important to fill the gap.

### First version: before end of September

Open tasks:
- [x] finish and merge initial version: https://github.com/owncloud/files_external_dropbox/pull/1 (see review comments)
- [x] take adapter from https://github.com/owncloud/core/pull/29077 and put it in this app's namespace for the first version. This makes it possible to release the app before 10.0.4 is ready.
- [ ] IMPORTANT: write a migration that switches every oc_external_config entry that has the old Dropbox backend to the one from this app
- [x] QA, changelog, info.xml, etc (talk to @pmaier1)
- [ ] Add CHANGELOG.md with version and release date
- [x] Sign and build tarball
- [x] release it to the marketplace
- [x] Rename QA milestone to $version and close it
- [ ] get https://github.com/owncloud/core/pull/29077 merged into core's master and stable10 for upcoming 10.0.4

### Second version: after 10.0.4 release
- [ ] remove flysystem caching adapter from the files_external_dropbox
- [ ] adjust files_external_dropbox to use core's flysystem caching adapter
- [ ] make second release to marketplace

For any reviews ping @jvillafanez and @DeepDiver1975

**Comment by PVince81** [comment]
cc @pmaier1

**Comment by PVince81** [comment]
@Hemant-Mann can you take care ?

**Comment by Hemant-Mann** [comment]
@PVince81 Caching adapter has been put in this app's namespace

**Comment by Hemant-Mann** [comment]
Review Comments are fixed
1) Added the missing tags in app config
2) Removed background job which was using the polling api

**Comment by hurradieweltgehtunter** [comment]
FYI: https://doc.owncloud.org/server/master/developer_manual/app/publishing.html
-> "Available product tags"
Screenshot(s) should be at 1400px width with an aspect ratio of 3:2
Description texts can be styled with markdown.

**Comment by davitol** [comment]
[WIP] TestPlan for new DropBox app: https://github.com/owncloud/QA/issues/494

**Comment by Hemant-Mann** [comment]
@hurradieweltgehtunter I used screenshot from this [https://github.com/owncloud/files_external_ftp](https://github.com/owncloud/files_external_ftp) app

**Comment by pmaier1** [comment]
marketing cleanup etc.: https://github.com/owncloud/files_external_dropbox/pull/5

**Comment by pmaier1** [comment]
I assume that on the technical side all is fine so far. Please double-check with the items in the list here @DeepDiver1975. -> Ready for release

**Comment by pmaier1** [comment]
Reopening for v2

**Comment by DeepDiver1975** [comment]
> Reopening for v2

new issue maybe? this issue is on milestone 1.0.0 which is released and closed?

**Comment by pmaier1** [comment]
Good point. https://github.com/owncloud/files_external_dropbox/issues/10
