### ISSUE TITLE
Dropbox setup with oC does not work by default

### ISSUE THREAD

**Issue by bobvandevijver** [owncloud/files_external_dropbox#20]
So, I've read #13, but I've also concluded that the fix there does not work for me. 

What I needed to do to make the authorization work:
1. Reload the code from `dropbox.js` in Chrome debugger after adding the new storage line. When you add a new storage line, the new row with `td.configuration` was not yet available for the script, resulting in the eventhandler not working.
2. Accept at dropbox
3. Break at the line firing the `oauth_step2` event (set this breakpoint before going to dropbox), [here](https://github.com/owncloud/core/blob/master/apps/files_external/js/oauth2.js#L37). During the break pause, load the same code as in step 1.
4. Congrats, you now have a functional dropbox connection!

The first issue arises due to to early event handling definition, the second on is probably a race condition due to the order of js-files being loaded.

I'm running Owncloud 10.0.4.4, just updated it today before testing from the Debian package.

**Comment by PVince81** [comment]
@bobvandevijver are you using the app from marketplace ? If yes, can you try building the app with `make` from this repository's master and try with that version ?

**Comment by bobvandevijver** [comment]
I'm using the marketplace app, but I've verified the event handler before creating this issue. As you can see in [dropbox.js](https://github.com/owncloud/files_external_dropbox/blob/3e1fa56db5cb4e0b4e737064fcd9da296704b983/js/dropbox.js), the handler is only executed once, at page load.

I've also verified this using the master version (I've confirmed it was updated, as the storage is now called 'Dropbox V2' due to [this commit](https://github.com/owncloud/files_external_dropbox/commit/1dd4d324fcce98a2f34a66c4d0be4b7e06eadc91)), it has the same issue. (not sure what you meant with `make` though, I've simply cloned and runned `composer install`).

**Comment by Hemant-Mann** [comment]
Hi @bobvandevijver I think this fiddle explains what is happening when you are trying to setup Dropbox
https://jsfiddle.net/82cwsprd/

@PVince81 the problem here is that https://github.com/owncloud/files_external_dropbox/blob/master/js/dropbox.js#L5
Here I am attaching events on elements like this `$('.configuration').on('oauth_step1'` but events are fired on dynamically created elements (which do not listen to these events)
https://github.com/owncloud/core/blob/master/apps/files_external/js/oauth2.js#L37

When I had originally submitted the pull request to core i was doing this `$('.configuration').trigger('oauth_step1',` which would work if you see my fiddle (https://jsfiddle.net/82cwsprd/)

This behaviour was changed in https://github.com/owncloud/core/pull/29145

**Comment by Hemant-Mann** [comment]
@PVince81 Thoughts?

**Comment by bcutter** [comment]
Wow that´s quite tough. I´m strongly interested in how to solve this. Followed I think three or four references to get here. Anything I can test or contribute?

**Comment by PVince81** [comment]
@Hemant-Mann for dynamically created elements, use delegates: http://api.jquery.com/on/ (search for "delegate"

Basically register the listener on a parent event but specify the child element's selector, so the handler will fire.

**Comment by Hemant-Mann** [comment]
@bcutter I have added a fix for the issue in #21 Could you try with that?

@PVince81 I have modified the selectors for listeners accordingly

**Comment by bobvandevijver** [comment]
I've just tested the fix, now it works correctly.

**Comment by Hemant-Mann** [comment]
Thanks @bobvandevijver for the quick response

**Comment by bcutter** [comment]
@Hemant-Mann 

Nope, still not working. To be more specific: Nothing happens after clicking "Grant access" (besides the button being greyed out and the status indicator spinning and ending in RED after few seconds).

I really checked every thing multiple times. App key and secret correct (tried copy + paste as well as typing). No errors in Owncloud Log (set to 'warning' log level).

**Comment by Hemant-Mann** [comment]
@bcutter Could you verify that **dropbox.js** loading is the new one having the changes of #21 ?

**Comment by bcutter** [comment]
How to check? There is another dropbox.js in „/files_external/...“ but so don’t know which one is used. Maybe Web Developer mode of Browser during loading the site?

**Comment by Hemant-Mann** [comment]
Check this image
<img width="1166" alt="js files" src="https://user-images.githubusercontent.com/10141396/34490412-d4418062-f005-11e7-9efa-358af9cc1c58.png">

**Comment by bcutter** [comment]
Well both dropbox.js files are loaded (upper line is loading ".../files_external/js/dropbox.js"

![unbenannt](https://user-images.githubusercontent.com/13799156/34491750-0215689e-efe5-11e7-9801-15e20c00f10a.png)

How to rule this out (besides deleting the "wrong"/old dropbox.js)?

**Comment by Hemant-Mann** [comment]
Your network panel says **304 Not Modified** for dropbox.js
please select the **Cache Deactivation** check box and reload the page

**Comment by bcutter** [comment]
No difference. Without cache I get two 200 GET. Same result.

**Comment by bcutter** [comment]
No I didn’t because I‘m no developer or web application expert. I asked two times how to rule out the second dropbox.js (why is it still there?) - no answer. Unfortunately I don’t have more time to test things - in some weeks I meanwhile spend more time fixing or working around bugs in OwnCloud and its applications than using OC productively.

Anyway, you guys will fix this without me I‘m sure. I‘m out.

**Comment by bobvandevijver** [comment]
I believe @Hemant-Mann posted an image on how to exactly check what content is served in the `dropbox.js` from the `files_external_dropbox` folder.

The `files_external/dropbox.js` file is a file which belongs to the Owncloud core (it's the original, outdated dropbox plugin which is no longer functional), so it actually has nothing to do with this project/plugin (which is probably why your question was ignored).

However, as you state that you're not a developer, debugging this might not be for you. You will first need to update the plugin from git, and then checkout the feature-branch. I assume that you simply installed the plugin from the market (as I did at first), so then you would first need to get the plugin directly from GitHub.

**Comment by PVince81** [comment]
Should be fixed through https://github.com/owncloud/files_external_dropbox/pull/21
