### ISSUE TITLE
Test files_external_dropbox 1.0.1

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/files_external_dropbox#22]
Bugs fixed: 
   https://github.com/owncloud/files_external_dropbox/issues/23
   https://github.com/owncloud/files_external_dropbox/issues/26
Bugs not fixed so far: 
   https://github.com/owncloud/files_external_dropbox/issues/27

| Test Case                                | Expected Result                          | Result         | Related Comment |
| ---------------------------------------- | ---------------------------------------- | -------------- | --------------- |
| **DropBox as external storage**          |                                          |                |                 |
|                                          |                                          |                |                 |
| Connect DropBox as external storage      | The file appears in server               | ✅  |                 |
| Create/upload file in DropBox as external storage | verify file exists on DropBox Backend    | ✅  | Very slow in comparison with old app.     |
| Edit a file in DropBox as external storage | Verify file is edited on DropBox Backend | ✅  | Edit too quickly (for example using text editor) leads to errors due to slowness         |
| Share file to User 2                     | The file is shared                       | ✅  |                 |
| Share file to an LDAP user               | The file is shared and it can be open/edited/downloaded | ✅  |                 |
| Share file from an LDAP user             | The file is shared and it can be open/edited/downloaded | ✅  |                 |                |
| Upload a file to DropBox backend         | verify file exists on oC webUI           | ✅  |                 |
| Rename file on DropBox backend           | Verify file is renamed on oC webUI       | ✅  |                 |
| Rename file on oC webUI                  | Verify file is renamed on DropBox backend | ✅  | Ignoring the lowercase problem, it works                |
| Delete a file via the webUI              | verify it goes to Deleted Items folder; verify it is removed from DropBox backend storage | ✅  | This is not working well enough, many times a warning appears because the file is locked. Maybe it is related with the latency.                |
| Restore file from the Deleted Items folder | verify it goes back to the proper location and the back end storage server | ✅  |                 |
| Delete DropBox as external storage       | The mount disappears from mount points listed in admin view | :construction: |                 |
| Edit some DropBox config fields of external storage mount point | Check that the changes are applied       | ✅  |                 |
| Create a file on the webUI in Dropbox    | verify there is no version               | ✅  |                 |
| Edit file on the webUI in Dropbox        | Verify version exists                    | ✅  |  Problems with locked files due to latency.               |
| Roll back to old version                 | Verify file is the old version           | ✅  | Problems with some files due to latency (they appeared as locked).                |
| Upload file on Dropbox back end.  Edit in webUI | verify Version exists                    | ✅  |                 |
| Allow users to mount external storage enabled. Connect Dropbox as external storage Personal mountpoint | Verify mountpoint can be created in users personal page | ✅ |                 |
| Allow users to mount external storage disabled. Try to connect Dropbox as external storage Personal mountpoint | Verify mountpoint cannot be created in users personal page | ✅ |                 |
| Allow users to mount external storage disabled for Dropbox. Try to connect Dropbox as external storage Personal mountpoint | Verify mountpoint cannot be created in users personal page | ✅  |                 |
|                                          |                                          |                |                 |

**Comment by SergioBertolinSG** [comment]
Final considerations: 

https://github.com/owncloud/files_external_dropbox/issues/27 - This one is almost fixed in https://github.com/owncloud/files_external_dropbox/pull/28 but it is still missing some control of the different case situation of two filenames, see comments https://github.com/owncloud/files_external_dropbox/pull/28#issuecomment-356669989 and https://github.com/owncloud/files_external_dropbox/pull/28#issuecomment-356673725


But the most important issue in my opinion is https://github.com/owncloud/files_external_dropbox/issues/26

The slowness in every operation makes this app totally annoying to use and sometimes leads to unexpected failures due to files locked.

**Comment by patrickjahns** [comment]
Closing with 1.0.1 release
