### ISSUE TITLE
Setting up dropbox storage returns a 422 status code and grant access doesn't redirect.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/files_external_dropbox#23]
### Steps to reproduce

0. Enable dropbox app. (release/1.0.1).
1. Having an external storage available in dropbox.com. Set it up in the storage section of admin settings.

### Expected behaviour
Click in "grant access" button  redirects to dropbox site to allow access.

### Actual behaviour
Grant access button doesn't redirect anywhere.

When completing the form we can see a POST request failing:

Request URL: HOST/index.php/apps/files_external/globalstorages
Request Method:POST
Status Code:422 Unprocessable Entity

Response:
{"message":"Unsatisfied authentication mechanism parameters"}

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.1

**Cache**
DB

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"needsDbUpgrade":false,"version":"10.0.4.4","versionstring":"10.0.4","edition":"Community","productname":"ownCloud"}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
Yes, dropbox.

**Are you using encryption:** 
No.

**Logs**
Nothing appears in the logs as warnings or errors.

### Client configuration

**Browser**
Chrome

**Comment by Hemant-Mann** [comment]
Hi @SergioBertolinSG I remember @PVince81 explaining in some issue that this request will result in 422 because storage is not yet authenticated or something (don't remember exactly why)

But **Grant Access** Button works for me
Could you verify that the dropbox.js loaded contains the changes of #21 ?

**Comment by davitol** [comment]
Works for me too using release/1.0.1 branch. If @SergioBertolinSG can reproduce it again please reopen it.

**Comment by SergioBertolinSG** [comment]
@Hemant-Mann yes, it is including changes from  #21 .

**Comment by SergioBertolinSG** [comment]
OK, I have seen this working when having two elements in the external storages list:

![screen shot 2018-01-09 at 10 13 50](https://user-images.githubusercontent.com/9048796/34713228-e5a8f5c2-f525-11e7-9fec-7a6015857e8d.png)

It should work also having only one element.

**Comment by Hemant-Mann** [comment]
Hi @SergioBertolinSG 
Could you provide a screenshot of Network Tab displaying the contents of **dropbox.js**?

**Comment by Hemant-Mann** [comment]
Because for me it works regardless of number of elements

**Comment by SergioBertolinSG** [comment]
I guess you mean debugger tab?

![screen shot 2018-01-09 at 12 06 06](https://user-images.githubusercontent.com/9048796/34718061-9798291a-f535-11e7-87de-8a5a3b33d028.png)

**Comment by Hemant-Mann** [comment]
I don't know it works for me
You can see there is one request that results in 422 and one request for getting OAuth2 URL
<img width="1191" alt="screen shot 2018-01-09 at 4 40 41 pm" src="https://user-images.githubusercontent.com/10141396/34718272-11b89b64-f55c-11e7-9bbb-77dbd65413ea.png">

**Comment by davitol** [comment]
@SergioBertolinSG @Hemant-Mann It works fine in oC core master version, but it is reproducible in 10.0.4 oC Core version

**Comment by PVince81** [comment]
I debugged this and you need to have both the GDrive backend existing and this app (master) to reproduce the issue.

When testing OC core master, the GDrive backend is gone (moved to separate repo), so the Dropbox auth works.

However when gdrive.js is there, it fails because the jquery event handler is returning `false`, which internally calls `event.preventDefault()` and `event.stopPropagation()` which means that the oauth jquery handler in dropbox.js is never called. This causes the error in question.

I'll submit a set of PRs for both Dropbox and GDrive to make sure we return without parameters instead of returning false.

**Comment by PVince81** [comment]
TODOs:
- [ ] GDrive app repo
- [ ] Dropbox app
- [ ] GDrive in stable10 (bundled)

**Comment by PVince81** [comment]
@Hemant-Mann please review all PRs from https://github.com/owncloud/files_external_dropbox/issues/23#issuecomment-356285214

@SergioBertolinSG can you retest with the PRs in question ? Make sure to retest both Dropbox and Gdrive

**Comment by Hemant-Mann** [comment]
@PVince81 i read your explanation regarding the issue, i remember reading something similar that returning false is supposed to do this.
If that's the case then PRs should fix the problem 
Reviewed all three

**Comment by PVince81** [comment]
Thanks.

For those who want the fix right away, need to patch core with https://github.com/owncloud/core/pull/30071 and use the dropbox app's release/1.0.1 branch.

**Comment by SergioBertolinSG** [comment]
Working fine with 10.0.4 + https://github.com/owncloud/core/pull/30071
And files_external_dropbox from release/1.0.1 branch + https://github.com/owncloud/files_external_dropbox/pull/24
