### ISSUE TITLE
Slow performance

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/files_external_dropbox#26]
This app depends on dropbox api responses and much of the retardation can come from Dropbox servers. But, using previous app we could navigate the files much more quickly. Obviously not as quickly as the local files view, but definitely faster than current approach.

Making some measurements (depending on the network, yes, but can show us an estimation):

```
./measure_upload_time.sh
Time taken: 12854 milliseconds
````

Being that script this code:

```
ts=$(gdate +%s%N)
curl -X PUT -u HIDDEN_USER:HIDDEN_PASSWORD --data-binary @"zombie.jpeg" "https://HIDDEN_HOST/remote.php/webdav/DropboxV2/zombie.jpeg"
tt=$((($(gdate +%s%N) - $ts)/1000000))
echo "Time taken: $tt milliseconds"
```

When using the interface we can see this slowness:

![propfind_interfaz_primera_parte](https://user-images.githubusercontent.com/9048796/34731470-b3e719b4-f562-11e7-9423-0d89ee7a0b58.gif)

it was too slow for one gif, second part:

![propfind_interfaz_segunda_parte](https://user-images.githubusercontent.com/9048796/34731490-c3ebbc84-f562-11e7-900d-51693ff10560.gif)

Around 50s in showing files.
 

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.0

**Cache**
DB

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"needsDbUpgrade":false,"version":"10.0.4.4","versionstring":"10.0.4","edition":"Community","productname":"ownCloud"}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
Yes, dropbox.

**Are you using encryption:** 
No.

**Logs**
Nothing appears in the logs as warnings or errors.

### Client configuration

**Browser**
Chrome

**Comment by Hemant-Mann** [comment]
@SergioBertolinSG Could you provide an estimate of number of files/folders in your Dropbox App?

Although I have written a Cacheable adapter on top of Flysystem adapter which will prevent multiple calls to API (which are sent by oC while fetching the metadata of files)

It may be related to trying to sync a large number of files for the first time

**Comment by SergioBertolinSG** [comment]
15 files, 1 folder with 4 files inside a subfolder.

**Comment by Hemant-Mann** [comment]
Oh that is not large.
Ok I will try to debug this

**Comment by SergioBertolinSG** [comment]
I have find that the file list loading is much faster in firefox 57.

**Comment by PVince81** [comment]
@Hemant-Mann pointed out that `file_exists` is not using the stat cache here: https://github.com/owncloud/files_external_dropbox/pull/28#issuecomment-361187696

So solving this will hopefully fix most performance issues.

**Comment by SergioBertolinSG** [comment]
Fixed in https://github.com/owncloud/files_external_dropbox/pull/29
