### ISSUE TITLE
 Can't integrate App

### ISSUE THREAD

**Issue by voroyam** [owncloud/files_external_dropbox#34]
Tested with DamkenCloud and a DropBox Account.

We have tried following the manual at:

https://doc.owncloud.com/server/10.0/admin_manual/configuration/files/external_storage/dropbox.html?highlight=dropbox

The redirect URL :

hostname
https://cloud.damken.com/index.php
hostname ... personal ....
https://cloud.damken.com/index.php/settings/personal?sectionid=storage
hostname ... admin ....
https://cloud.damken.com/index.php/settings/admin?sectionid=storage

no success so far.

Tested with the current version of the App.

Tested with Firefox (With Adblock) and Chrom (clean installation) in normal and private Windows.

![drop](https://user-images.githubusercontent.com/24212810/36311050-48938694-132a-11e8-9002-a49fb1371f5f.png)

**Comment by Hemant-Mann** [comment]
@voroyam Could you provide some more details like 
- Contents of owncloud.log
- owncloud version
- Any error message displayed while integrating the app

**Comment by voroyam** [comment]
Yeah, about that:
There is nothing in the log. 
I tried it yesterday with a service that tunnels the localhost outside. something "ngorg".
I could integrate the dropbox app with 10.0.6 and 10.0.4 and @IljaN managed it even with 10.0.7.
In all the cases no message was given in the owncloud.log. I tried to enter the redirect URL as just the host name, like it's described in the documentation, to provoke an error, but even then nothing went to the log at log level 0.
I don't know why it sometimes works and sometimes not.

We tried it on damkenCloud, with the admin audit app enabled, and could see an "service temporary not available" message, but nothing more. In oc_storages was no entry about the new share.

There are no error messages while integrating the app.

After you enter all the informations, and click on "grant access" you sometimes get redirected to allow dropbox the access, but sometimes nothing happens at all. this was tested on damkencloud with 10.0.4 and on a local docker installation with 10.0.4 and 10.0.6

**Comment by voroyam** [comment]
issue can be closed, tests were successful. Maybe dropbox had a bug for one day.

**Comment by patrickjahns** [comment]
@voroyam 

I've seen the following behavior with dropbox - that might cause irritation with users
- propagation delay (when first creating a new app / changing the secret/key it takes some time for dropbox to actually work with them)
- copy+pasting key/secret from the dropbox website sometimes seem to add extra (whitespace?) chars - thus also failing
=> It quite often helps to copy+paste key/secet into a text-editor beforehand

**Comment by voroyam** [comment]
Okay, but have you an explanation for ownCloud not responding?

You enter all the credentials, click on grant access, maybe get redirected to drop box, allow the access there, then the share is still red, you click on grant access again and nothing happens.

or you just fail the first time, get no redirect, and nothing happens.

no errors in the log file.

It's weird that it works now and did not work a week ago. My guess is that drop box has changed something on their end, because we did not change anything on ours. Also @IljaN still has / had issues with his share as a users.

**Comment by IljaN** [comment]
- I can consistently mount a dropbox share as an admin for all users without problems (Storage under Admin Options)
- The storage option under User Settings fails for some reasons, @cdamken  even managed to bring the ui in a inconsistent state.

**Comment by patrickjahns** [comment]
@IljaN 
Please provide some steps to reproduce

**Comment by patrickjahns** [comment]
@IljaN 
any update here?

**Comment by tomneedham** [comment]
I can reproduce in my production instance. I click 'grant access' and it just greys out and nothing happens.

**Comment by tomneedham** [comment]
Yes, upgrading core/app fixed this.

**Comment by IljaN** [comment]
Works! 

![dboxworks](https://user-images.githubusercontent.com/246983/38731384-43a441fc-3f1a-11e8-9fff-e9102a38fb86.png)

@voroyam We might need to update docs to include two redirect-urls in dropbox app settings

https://374a2caa.ngrok.io/index.php/settings/admin?sectionid=storage 
https://374a2caa.ngrok.io/index.php/settings/personal?sectionid=storage

Depending if you create a global or personal ext. storage different redirect urls are used

**Comment by voroyam** [comment]
docs were updated :)
