### ISSUE TITLE
Avoid packaging vcs files for composer dependencies

### ISSUE THREAD

**Issue by patrickjahns** [owncloud/files_external_dropbox#40]
The current released dropbox app contains the vcs directories at `vendor\hemant-mann\flysystem-dropbox\.git\` and `vendor\kunalvarma05\dropbox-php-sdk\.git\`.

We shall not include those in the release tarball

**Comment by cdamken** [comment]
@PVince81 could we release a new tar (even with the same version?

**Comment by PVince81** [comment]
I think we should release a new version anyway soon as we have pending changes and need a re-release for the semver changes.

If this is bothersome I can increase priority and have this out without the semver bits.

**Comment by PVince81** [comment]
makefile fix here: https://github.com/owncloud/files_external_dropbox/pull/41
