### ISSUE TITLE
Tracking results for Dropbox External Storage Release 1.1.0

### ISSUE THREAD

**Issue by davitol** [owncloud/files_external_dropbox#44]
## Previous requirements

Tested with stable10 tarball and the Dropbox app tarball located in: https://cloud.owncloud.com/index.php/s/KTwSnsPUmccpQpQ

Enable LDAP, external storage, 

Have a LDAP server ready to be used with owncloud.

Have ready Dropbox external storage configuration.

## Testing setup

TestID | Test Case | Expected Result | Result | Related Comment
------------ | ------------- | -------------- | ----- | ------
 |  |  |   |
 | **DropBox as external storage** |  |   |
 |  |  |   |
1 | Connect DropBox as external storage | The MountPoint appears in server | ✅    |
2 | Create/upload file in DropBox as external storage | verify file exists on DropBox Backend | ✅  |
3 | Edit a file in DropBox as external storage | Verify file is edited on DropBox Backend | ✅  |
4 | Share file to User 2 | The file is shared | ✅  |
5 | Share file to an LDAP user | The file is shared and it can be open/edited/downloaded | ✅  |
6 | Share file from an LDAP user | The file is shared and it can be open/edited/downloaded | ✅  |
7 | Upload a file to DropBox backend | verify file exists on oC webUI| ✅  |
8 | Rename file on DropBox backend  | Verify file is renamed on oC webUI | ✅  |
9 | Rename file on oC webUI  | Verify file is renamed on DropBox backend | ✅  |
10 | Delete a file via the webUI  | verify it goes to Deleted Items folder; verify it is removed from DropBox backend storage | ✅  |
11 | Restore file from the Deleted Items folder  | verify it goes back to the proper location and the back end storage server |  ✅ |
12 | Connect DropBox as external storage in a oC server 10.0.10 and  try to upgrade to oC Master (11.0.0)| Check that config still exists and works | ✅  |
13 | Connect DropBox as external storage in a oC server 10.0.9 and upgrade to oC 10.0.10 | Check that config still exists and works |  ✅  |
14 | Delete DropBox as external storage | The mount disappears from mount points listed in admin view | ✅ |
15 | Edit some DropBox config fields of external storage mount point | Check that the changes are applied |  ✅  |
16 | Create a file on the webUI in Dropbox | verify there is no version  | ✅  |
17 | Edit file on the webUI in Dropbox | Verify version exists | ✅   |
18 | Roll back to old version | Verify file is the old version | ✅  |
19 | Upload file on Dropbox back end.  Edit in webUI | verify Version exists | ✅  |
20 | Allow users to mount external storage enabled. Connect Dropbox as external storage Personal mountpoint | Verify mountpoint can be created in users personal page | ✅ |
21 | Allow users to mount external storage disabled. Try to connect Dropbox as external storage Personal mountpoint | Verify mountpoint cannot be created in users personal page | ✅ |
22 | Allow users to mount external storage disabled for Dropbox. Try to connect Dropbox as external storage Personal mountpoint | Verify mountpoint cannot be created in users personal page | ✅  |
23 | Share a file located in a DropBox mount using 'Share via link' | Check the link works and the file can  be downloaded | ✅  |
24 | With Activity app enable, edit a file located in a DropBox mount| Check the activity is registered and the link to the file location works| ✅  |

**Comment by PVince81** [comment]
- [ ] check items from https://github.com/owncloud/files_external_dropbox/issues/37

@davitol mind checking the above as well ? they could become more bug reports...

**Comment by davitol** [comment]
Favorite mountpoints is not working properly
![favorite](https://user-images.githubusercontent.com/10596560/50001867-8371f780-ff9e-11e8-8e10-afc5c07da321.gif)

**Comment by davitol** [comment]
> @davitol mind checking the above as well ? they could become more bug reports...

https://github.com/owncloud/files_external_dropbox/issues/37#issuecomment-447268760
