### ISSUE TITLE
[PHP 7.3 comp] Files External Dropbox 1.2.0

### ISSUE THREAD

**Issue by phil-davis** [owncloud/files_external_dropbox#69]
### Reason
With PHP 7.3 there are warnings like:
```
{
  "reqId": "OoqH1KticTibviWCoT99",
  "level": 3,
  "time": "2019-10-30T20:55:02+01:00",
  "remoteAddr": "",
  "user": "--",
  "app": "PHP",
  "method": "--",
  "url": "--",
  "message": ""continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? at /var/www/owncloud/apps/files_external_dropbox/vendor/guzzlehttp/ringphp/src/Client/CurlFactory.php#382"
}
```

The current release of this app has `guzzlehttp/ringphp` 1.1.0

https://github.com/guzzle/RingPHP/releases/tag/1.1.1 has the PHP 7.3 changes, in particular https://github.com/guzzle/RingPHP/commit/80d4890f0770a67ab27d839df9db7f04268d0eb7 which will fix that warning.

That is in `master` of this app, but has not been released.

### QA

- [x] Create **QA** Milestone and set the description to $version
- [x] Move items from `development` to `qa`
- [x] Create release branch with the format "release-$version"
- [x] Create "1.2.0 Testplan" @davitol https://github.com/owncloud/files_external_dropbox/issues/75

### Documentation

- [ ] Changes in the docs needed?

### Marketing

- [ ] Ping @owncloud/marketing
- [ ] Check/adapt info.xml stuff
- [ ] Check/adapt screenshot
- [ ] Blog post or other communication if applicable

### Build

All actions to be done on the release branch from here:
- [x] Bump version in info.xml (no version suffix)
- [x] Update CHANGELOG.md - Change CHANGELOG.md 'Unreleased' to '$version' (final release date unknown)

#### Beta/RC

- [x] Create github tag for 'v${version}RC1' on release branch
- [x] Build and sign RC tarball from github tag 'v${version}RC1' (see
  handbook for how to build)
- [x] Upload as Github release using changelog entries
- [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) @davitol  https://github.com/owncloud/files_external_dropbox/issues/75h

#### Final

- [x] Create github tag for final 'v${version}' on release branch
- [x] Build and sign final tarball from github tag 'v${version}' (see
  handbook for how to build)
- [x] Upload as Github release using changelog entries
- [x] Smoke test tarball (at least install + enable)

### Publishing

- [x] Upload tarball to marketplace (see handbook for details)
- [x] Publish tarball for customers (see handbook for details)
- [x] Send mail to release-coordination with link to this ticket and to the changelog

### Post-release

- [x] Rename QA milestone to '$version'
- [x] Add a new 'Unreleased' section in CHANGELOG.md and add release date '$version - $currentDate' (ex: 3.1.5 - 2018-08-01)
- [x] Create PR to merge changes back to the `master` branch with
  description "Closes #XYZ" with the release ticket number

**Comment by micbar** [comment]
@davitol RC1 in https://github.com/owncloud/files_external_dropbox/releases/tag/v1.2.0RC1

**Comment by davitol** [comment]
> @davitol RC1 in https://github.com/owncloud/files_external_dropbox/releases/tag/v1.2.0RC1

@micbar Tarball is QA-ready see results here: https://github.com/owncloud/files_external_dropbox/issues/75

**Comment by micbar** [comment]
Done.
