### ISSUE TITLE
Tracking results for Dropbox External Storage Release 1.2.0

### ISSUE THREAD

**Issue by davitol** [owncloud/files_external_dropbox#75]
## Previous requirements

Enable LDAP, external storage, 

Have a LDAP server ready to be used with owncloud.

Have ready Dropbox external storage configuration.

## Testing setup

TestID | Test Case | Expected Result | Result | Related Comment
------------ | ------------- | -------------- | ----- | ------
 |  |  |   |
 | **DropBox as external storage** |  |   |
 |  |  |   |
1 | Connect DropBox as external storage | The MountPoint appears in server | ✅    |
2 | Create/upload file in DropBox as external storage | verify file exists on DropBox Backend | ✅  |
3 | Edit a file in DropBox as external storage | Verify file is edited on DropBox Backend | ✅  |
4 | Share file to User 2 | The file is shared | ✅  |
5 | Share file to an LDAP user | The file is shared and it can be open/edited/downloaded | ✅  |
6 | Share file from an LDAP user | The file is shared and it can be open/edited/downloaded | ✅  |
7 | Upload a file to DropBox backend | verify file exists on oC webUI| ✅  |
8 | Rename file on DropBox backend  | Verify file is renamed on oC webUI | ✅  |
9 | Rename file on oC webUI  | Verify file is renamed on DropBox backend | ✅  |
10 | Delete a file via the webUI  | verify it goes to Deleted Items folder; verify it is removed from DropBox backend storage | ✅  |
11 | Restore file from the Deleted Items folder  | verify it goes back to the proper location and the back end storage server |  ✅ |
12 | Connect DropBox as external storage in a oC server 10.2.1 and  try to upgrade to oC 1.3.2| Check that config still exists and works |✅  |
13 | Delete DropBox as external storage | The mount disappears from mount points listed in admin view | ✅ |
14 | Edit some DropBox config fields of external storage mount point | Check that the changes are applied |  ✅  |
15 | Create a file on the webUI in Dropbox | verify there is no version  | ✅  |
16 | Edit file on the webUI in Dropbox | Verify version exists | ✅   |
17 | Roll back to old version | Verify file is the old version | ✅  |
18 | Upload file on Dropbox back end.  Edit in webUI | verify Version exists | ✅  |
19 | Allow users to mount external storage enabled. Connect Dropbox as external storage Personal mountpoint | Verify mountpoint can be created in users personal page | ✅ |
20 | Allow users to mount external storage disabled. Try to connect Dropbox as external storage Personal mountpoint | Verify mountpoint cannot be created in users personal page | ✅ |
21 | Allow users to mount external storage disabled for Dropbox. Try to connect Dropbox as external storage Personal mountpoint | Verify mountpoint cannot be created in users personal page | ✅  |
22 | Share a file located in a DropBox mount using 'Share via link' | Check the link works and the file can  be downloaded | ✅  |
23 | With Activity app enable, edit a file located in a DropBox mount| Check the activity is registered and the link to the file location works| 🚧   |

**Comment by davitol** [comment]
### Changelog

## [1.2.0]

### Changed
- Update dependencies - [#70](https://github.com/owncloud/files_external_dropbox/issues/70)
- Composer dependency bumps 20190730 - [#62](https://github.com/owncloud/files_external_dropbox/issues/62)
- Composer dependency bumps 20190529 - [#61](https://github.com/owncloud/files_external_dropbox/issues/61)
- Drop PHP 5.6 - [#55](https://github.com/owncloud/files_external_dropbox/issues/55) **To be deleted from changelog**

**Comment by micbar** [comment]
Done
